In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [ ]:
train_df=pd.read_csv('/content/fraudTrain.csv')

In [ ]:
test_df=pd.read_csv('/content/fraudTest.csv')

In [ ]:
train_df.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0    3495.0          Psychologist, counselling  1988-03-09   
1     149.0  Special educational needs teacher  1978-06-21   
2    4154.0        Nature conservation officer  1962-01-19   
3    1939.0                    Patent attorney  1967-01-12   
4      99.0     Dance movement psychotherapist  1986-03-28   

                          trans_num     unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1.325376e+09  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1.325376e+09  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1.325376e+09  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1.325376e+09  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1.325376e+09  38.674999  -78.632459   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [ ]:
test_df.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0  333497.0     Mechanical engineer  1968-03-19   
1     302.0  Sales professional, IT  1990-01-17   
2   34496.0       Librarian, public  1970-10-21   
3   54767.0            Set designer  1987-07-25   
4    1126.0      Furniture designer  1955-07-06   

                          trans_num     unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1.371817e+09  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1.371817e+09  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1.371817e+09  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1.371817e+09  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1.371817e+09  44.959148  -85.884734   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [ ]:
train_df.shape

(108881, 23)

In [ ]:
test_df.shape

(124327, 23)

In [ ]:
for df in [train_df, test_df]:
    df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
    df['hour'] = df['trans_date_trans_time'].dt.hour
    df['day'] = df['trans_date_trans_time'].dt.day
    df['weekday'] = df['trans_date_trans_time'].dt.weekday
    df.drop(columns=['trans_date_trans_time'], inplace=True)


In [ ]:
drop_cols = ['first', 'last', 'dob', 'trans_num', 'cc_num', 'street', 'unix_time']
train_df.drop(columns=drop_cols, inplace=True)
test_df.drop(columns=drop_cols, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

categorical_cols = ['merchant', 'category', 'gender', 'city', 'state', 'job']

le = LabelEncoder()
for col in categorical_cols:
    # Convert all values to string before encoding
    train_df[col] = train_df[col].astype(str)
    test_df[col] = test_df[col].astype(str)

    # Combine train and test data for fitting
    combined_data = pd.concat([train_df[col], test_df[col]], axis=0)
    le.fit(combined_data)

    # Transform train and test data
    train_df[col] = le.transform(train_df[col])
    test_df[col] = le.transform(test_df[col])

In [ ]:
# Drop rows with missing values in 'is_fraud'
train_df.dropna(subset=['is_fraud'], inplace=True)
test_df.dropna(subset=['is_fraud'], inplace=True)

X_train = train_df.drop(columns=['is_fraud'])
y_train = train_df['is_fraud']

X_test = test_df.drop(columns=['is_fraud'])
y_test = test_df['is_fraud']

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
import numpy as np

# Impute missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)


lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_imputed, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [ ]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)


DecisionTreeClassifier()

In [ ]:
rf_model = RandomForestClassifier(n_estimators=100)
rf_model.fit(X_train, y_train)


RandomForestClassifier()

In [ ]:
models = {'Logistic Regression': lr_model, 'Decision Tree': dt_model, 'Random Forest': rf_model}

for name, model in models.items():
    print(f"\n{name}")
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))



Logistic Regression
Accuracy: 0.9945707253510931
[[123648    185]
 [   490      3]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    123833
         1.0       0.02      0.01      0.01       493

    accuracy                           0.99    124326
   macro avg       0.51      0.50      0.50    124326
weighted avg       0.99      0.99      0.99    124326


Decision Tree


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


Accuracy: 0.9953348454868651
[[123419    414]
 [   166    327]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    123833
         1.0       0.44      0.66      0.53       493

    accuracy                           1.00    124326
   macro avg       0.72      0.83      0.76    124326
weighted avg       1.00      1.00      1.00    124326


Random Forest
Accuracy: 0.9979087238389396
[[123798     35]
 [   225    268]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    123833
         1.0       0.88      0.54      0.67       493

    accuracy                           1.00    124326
   macro avg       0.94      0.77      0.84    124326
weighted avg       1.00      1.00      1.00    124326



In [ ]:
X_train.head()

Unnamed: 0  merchant  category     amt  gender  city  state      zip  \
0           0       515         8    4.97       0   501     26  28654.0   
1           1       241         4  107.23       0   577     46  99160.0   
2           2       391         0  220.11       1   447     12  83252.0   
3           3       360         2   45.00       1    81     25  59632.0   
4           4       297         9   41.96       1   205     44  24433.0   

       lat      long  city_pop  job  merch_lat  merch_long  hour  day  weekday  
0  36.0788  -81.1781    3495.0  360  36.011293  -82.048315     0    1        1  
1  48.8878 -118.2105     149.0  415  49.159047 -118.186462     0    1        1  
2  42.1808 -112.2620    4154.0  298  43.150704 -112.154481     0    1        1  
3  46.2306 -112.1138    1939.0  319  47.034331 -112.561071     0    1        1  
4  38.4207  -79.4629      99.0  112  38.674999  -78.632459     0    1        1